### ISSUE TITLE
Nice work guys ;)

### ISSUE THREAD

**Issue by dylanvorster** [stimpack-io/stimpack#1]
Just wanted to say thanks for using storm-react-diagrams! I hope the library didn't give you too many issues and thanks for also sticking it out!

I have a long history in PHP7 development, and cant wait to see your project really take off, it looks really cool so far, and I'm especially glad you used it in a very declarative way :D

**Comment by ajthinking** [comment]
Wow, thanks for your encouraging words! You and your library are true inspirations for us, glad you find your way here :)

So the usage of [react-diagrams](https://github.com/projectstorm/react-diagrams) went really smooth, will certainly use again whenever possible. At the moment im on a vacation, but hope to keep this project alive and progressing. Kickstarter campaign will likely not provide the funding required to allocate full time on this project, though we hope to attract some more contributors to keep it going. 

Its funny, came to mind a couple of years ago I had a idea of making a geography/shape-manipulating flowchart for browser usage. Kind of like this <img src="https://images.safe.com/photos/features/fme-desktop-transform.jpg" /> At the time i thought this was TOTALLY IMPOSSIBLE and a newbie FANTASY. But now with react-diagrams, we've done it (for code generation instead). Pretty cool how dreams come true in new forms!
